### ISSUE TITLE
feature request: add __get, __set, __call

### ISSUE THREAD

**Issue by leohearts** [ProbiusOfficial/PHPSerialize-labs#6]
### `__get` and `__set`

```php
<?php 
class Test {
    public $abc = 123;
    public $ddd = 234;
    function __get($name){
        print_r("__get");
        var_dump($name);
        return 1337;
    }
    
    function __set($name, $value){
        print_r("__set");
        $this->$name = $value;
        var_dump($name, $value);
    }
}

$i = new Test();
var_dump($i);
var_dump($i->abc);
var_dump($i->flag);


$i->ddd = 1338;
var_dump($i->ddd);
$i->f10g = 234;
var_dump($i->f10g);
```

### `__call` could be added with `__invoke` 

```php
<?php 
highlight_file(__FILE__);
class FLAG {
    function test() {
        var_dump('test');
    }
    function __call($method, $args) {
        var_dump('call ' . $method . ' with args ' . print_r($args, true));
    }
    function __invoke() {
        var_dump('invoke'); // won't fallback to __call, if undefined
    }
}
$x = new FLAG();
$x -> test();
$x -> flag("123", 234, array(4,5,6));
$x();
```

code should be adjusted to work as a ctf problem, but I'm sure where should put it in (between 14 and 15 maybe?)

**Comment by ProbiusOfficial** [comment]
The magic methods mentioned in the challenge are only partially included to lead into the subsequent pop part. In the first magic method tutorial level, I provided the PHP manual because I wanted the participants to look it up themselves. However, there is indeed a difference between development and solving challenges. If we insert the content about magic methods directly here, the labs might become a bit bloated. That said, I strongly advocate adding this content. Perhaps we can create a new section specifically for practicing magic methods at the bottom of the labs? On second thought, as a learning playground, directly adding these questions wouldn't be a big issue either.
